[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Milk-Outside-a-Bag-of Milk
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=Milk-Outside-a-Bag-of Milk
GtkTheme=Milk-Outside-a-Bag-of Milk
IconTheme=Milk-Outside-a-Bag-of Milk
MetacityTheme=Milk-Outside-a-Bag-of Milk
